name: build-ig

on:
  push:
  workflow_dispatch:

jobs:
  sushi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Jekyll
        run: sudo gem install jekyll

      - name: Install Sushi
        run: sudo npm install -g fsh-sushi

      - name: Validate with Sushi
        run: sushi .

  ig-publisher:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Jekyll
        run: sudo gem install jekyll

      - name: Install Sushi
        run: sudo npm install -g fsh-sushi
      
      - name: Install IG publisher
        run: |
          # sudo apt-get -y install iputils-ping
          chmod +x ./_updatePublisher.sh
          ./_updatePublisher.sh -y
